baseURL = "http://engstrand.nu/"
languageCode = "en-us"
title = "Johan Engstrand"
theme = "awesome-identity"

## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "Johan"
  lastname = "Engstrand"
  title = "Engineer"
  bio = "hej"


## Footer Configurations
[params.footer]
  copyright = "© 2019 Byungjin Park. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
